import discord

embed1 = discord.Embed(title="Help (1/5)", description="List of available commands:", color=0x00ff00)
embed1.add_field(name="!create_connection <device_index> <ip> <username> <password>", value="Add a device to connection list", inline=False)
embed1.add_field(name="!show_connection <device_index>", value="Show all connected devices", inline=False)
embed1.add_field(name="!ping <device_index> <ip_dest>", value="Ping an IP address", inline=False)
embed1.add_field(name="!traceroute <device_index> <ip_dest> <source_ip (Optional)>", value="Trace route to an IP address", inline=False)
embed1.add_field(name="!show_hostname <device_index>", value="Show hostname of a device", inline=False)
embed1.add_field(name="!show_int <device_index>", value="Show interface status", inline=False)
embed1.add_field(name="!show_vlan <device_index>", value="Show VLAN information", inline=False)
embed1.add_field(name="!show_run <device_index>", value="Show running configuration", inline=False)
embed1.add_field(name="!show_run_int <device_index> <interface>", value="Show interface configuration", inline=False)
embed1.add_field(name="!save_config <device_index>", value="Save running configuration", inline=False)

embed2 = discord.Embed(title="Help (2/5)", description="List of available commands:", color=0x00ff00)
embed2.add_field(name="!hostname <device_index> <hostname>", value="Set device hostname", inline=False)
embed2.add_field(name="!show_route <device_index>", value="Show IP routing table", inline=False)
embed2.add_field(name="!create_route <device_index> <dest_ip> <dest_mark> <next_hop>", value="Add IP route", inline=False)
embed2.add_field(name="!show_spanning_tree <device_index>", value="Show spanning tree information", inline=False)
embed2.add_field(name="!banner <device_index> <str>", value="Set banner message", inline=False)
embed2.add_field(name="!create_vlan <device_index> <vlan_number>", value="Create a new VLAN", inline=False)
embed2.add_field(name="!vlan_ip_add <device_index> <vlan_number> <ip_addr> <netmask>", value="Add IP address to VLAN", inline=False)
embed2.add_field(name="!vlan_no_shut <device_index> <vlan_number>", value="No shutdown VLAN", inline=False)
embed2.add_field(name="!delete_vlan <device_index> <vlan_number>", value="Delete VLAN", inline=False)
embed2.add_field(name="!int_ip_add <device_index> <interface> <ip> <mask>", value="Add IP address to interface", inline=False)

embed3 = discord.Embed(title="Help (3/5)", description="List of available commands:", color=0x00ff00)
embed3.add_field(name="!add_gateway <device_index> <ip_gateway>", value="Set default gateway", inline=False)
embed3.add_field(name="!delete_gateway <device_index> <ip_gateway>", value="Delete default gateway", inline=False)
embed3.add_field(name="!int_switch_mode <device_index> <interface> <mode>", value="Set interface switchport mode", inline=False)
embed3.add_field(name="!int_no_shut <device_index> <interface>", value="No shutdown interface", inline=False)
embed3.add_field(name="!int_shut <device_index> <interface>", value="Shutdown interface", inline=False)
embed3.add_field(name="", value="", inline=False)
embed3.add_field(name="!rip <device_index> <network_ip,network_ip2,...>", value="Create/Add RIP network", inline=False)
embed3.add_field(name="!remove_rip_nw <device_index> <network_ip>", value="Remove RIP network", inline=False)
embed3.add_field(name="!disable_rip <device_index>", value="Disable RIP Routing Protocol", inline=False)
embed3.add_field(name="!show_rip <device_index>", value="show ip rip neighbor", inline=False)
embed3.add_field(name="", value="", inline=False)
embed3.add_field(name="!ospf <device_index> <network_ip/netmask(1-32)/area,network_ip2/netmask2(1-32)/area2,...>", value="Create/Add OSPF network", inline=False)
embed3.add_field(name="!remove_ospf_nw <device_index> <network_ip/netmask(1-32)/area>", value="Remove OSPF network", inline=False)
embed3.add_field(name="!disable_ospf <device_index>", value="Disable OSPF Routing Protocol", inline=False)

embed4 = discord.Embed(title="Help (4/5)", description="List of available commands:", color=0x00ff00)
embed4.add_field(name="!show_ospf <device_index>", value="show ip ospf neighbor", inline=False)
embed4.add_field(name="", value="", inline=False)
embed4.add_field(name="!eigrp <device_index> <network_ip/netmask(1-32),network_ip2/netmask2(1-32),...> <as>", value="Create/Add EIGRP network", inline=False)
embed4.add_field(name="!remove_eigrp_nw <device_index> <network_ip/netmask(1-32)> <as>", value="Remove EIGRP network", inline=False)
embed4.add_field(name="!disable_eigrp <device_index> <as>", value="Disable EIGRP Routing Protocol", inline=False)
embed4.add_field(name="!show_eigrp <device_index>", value="show ip eigrp neighbor", inline=False)
embed4.add_field(name="", value="", inline=False)
embed4.add_field(name="!bgp <device_index> <network_ip/netmask(1-32),network_ip2/netmask2(1-32),...> <neighbor_ip:neighbor_as> <as>", value="Create/Add BGP network", inline=False)
embed4.add_field(name="!remove_bgp_nw <device_index> <network_ip/netmask(1-32)> <as>", value="Remove BGP network", inline=False)
embed4.add_field(name="!remove_bgp_neighbor <device_index> <neighbor_ip:neighbor_as> <as>", value="Remove BGP neighbor", inline=False)
embed4.add_field(name="!disable_bgp <device_index> <as>", value="Disable BGP Routing Protocol", inline=False)
embed4.add_field(name="!show_bgp <device_index>", value="show ip bgp summary", inline=False)
embed4.add_field(name="", value="", inline=False)
embed4.add_field(name="!delete_route <device_index> <dest_ip> <dest_mask> <next-hop>", value="Delete route", inline=False)
embed4.add_field(name="!vlan_ip_delete <device_index> <vlan_id>", value="Delete IP from the specified VLAN", inline=False)

embed5 = discord.Embed(title="Help (5/5)", description="List of available commands:", color=0x00ff00)
embed5.add_field(name="!int_ip_delete <device_index> <interface>", value="Delete IP from the specified interface", inline=False)
embed5.add_field(name="!int_access_vlan <device_index> <interface> <vlan_id>", value="Assign a specific VLAN to an interface.", inline=False)
embed5.add_field(name="!show_mac_table <device_index>", value="Show MAC Address table", inline=False)
embed5.add_field(name="!vlan_shut <device_index> <vlan_id>", value="Shutdown VLAN", inline=False)
embed5.add_field(name="!router_on_a_stick <device_index> <interface> <vlan_id> <ip_addr> <mask>", value="Create sub-interface on a router", inline=False)


pages = [embed1, embed2, embed3, embed4, embed5]

def get_help_page(num):
    return pages[num-1]